# Generated by Django 4.2 on 2023-04-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.CharField(max_length=10),
        ),
    ]
