# Generated by Django 4.2 on 2023-04-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_store_description_alter_store_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.CharField(max_length=37),
        ),
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='store',
            name='part_number',
            field=models.CharField(max_length=10),
        ),
    ]
